name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  SOURCE_BUCKETS: ${{ secrets.SOURCE_BUCKETS }}
  CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}
  DEMO_UI: ${{ vars.DEMO_UI }}

jobs:
  pipeline-job:
    name: Pipeline Job
    if: github.repository_owner == 'GeKorm'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DISPATCHER_ROLE_ARN }}
          aws-region: ${{ secrets.REGION }}
          role-duration-seconds: 900
          role-session-name: OIDCSession
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm' # Cache dependencies
      - name: Run tests
        run: cd deployment/ && chmod +x run-unit-tests.sh && ./run-unit-tests.sh
      - name: Install dependencies
        run: cd ../source/constructs && npm run clean:install
      - name: Bootstrap
        run: overrideWarningsEnabled=false npm run cdk -- bootstrap
      - name: Deploy without domain
        if: !${{ secrets.CUSTOM_DOMAIN }}
        run: overrideWarningsEnabled=false npm run cdk -- deploy --parameters DeployDemoUIParameter=$DEMO_UI --parameters SourceBucketsParameter=$SOURCE_BUCKETS
      - name: Deploy with custom domain
        if: ${{ secrets.CUSTOM_DOMAIN }}
        run: overrideWarningsEnabled=false npm run cdk -- deploy --parameters DeployDemoUIParameter=$DEMO_UI --parameters CustomDomainParameter=$CUSTOM_DOMAIN --parameters SourceBucketsParameter=$SOURCE_BUCKETS
